input {
    kb_layout = fr
    kb_variant =
    kb_model = pc105
    kb_options = grp:alt_shift_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        tap-to-click = true
        natural_scroll = true
        disable_while_typing = false
        scroll_factor = 1.0
        clickfinger_behavior = true
    }
}

device {
    name = syn1b7f:00-06cb:7dac-touchpad
    tap-to-click = true
    natural_scroll = true
    disable_while_typing = false
    scroll_factor = 1.0
    clickfinger_behavior = true
}
